<?php
namespace App\Services;
use App\Models\AiFeedback;
use App\Models\FarastFeedbackEvidence;
use Illuminate\Support\Facades\DB;
class FeedbackPipelineService {
 public function record(AiFeedback $feedback,?string $toolCode=null,?string $toolVersion=null,array $inputMeta=[],array $outputMeta=[],string $evidenceType='user_feedback'):FarastFeedbackEvidence{
  $toolId=$toolCode?DB::table('farast_tools')->where('code',$toolCode)->value('id'):null;$versionId=$toolVersion&&$toolId?DB::table('farast_tool_versions')->where('tool_id',$toolId)->where('version',$toolVersion)->value('id'):null;
  $checksum=hash('sha256',json_encode([$feedback->id,$inputMeta,$outputMeta],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));
  return FarastFeedbackEvidence::create(['feedback_id'=>$feedback->id,'tool_id'=>$toolId,'tool_version_id'=>$versionId,'evidence_type'=>$evidenceType,'input_meta'=>$inputMeta,'output_meta'=>$outputMeta,'confidence'=>$feedback->rating?((int)$feedback->rating/5):null,'status'=>'raw','checksum'=>$checksum]);
 }
 public function queueReview(FarastFeedbackEvidence $evidence):int{return (int)DB::table('farast_review_cases')->insertGetId(['evidence_id'=>$evidence->id,'status'=>'queued','created_at'=>now(),'updated_at'=>now()]);}
 public function approve(int $reviewId,int $reviewerId,string $capability,array $content,string $version='1.0.0'):void{DB::transaction(function()use($reviewId,$reviewerId,$capability,$content,$version){DB::table('farast_review_cases')->where('id',$reviewId)->update(['reviewer_id'=>$reviewerId,'decision'=>'approved','status'=>'approved','reviewed_at'=>now(),'updated_at'=>now()]);$checksum=hash('sha256',json_encode($content,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));DB::table('farast_approved_knowledge')->insert(['review_case_id'=>$reviewId,'capability_code'=>$capability,'knowledge_version'=>$version,'content'=>json_encode($content,JSON_UNESCAPED_UNICODE),'status'=>'approved','approved_by'=>$reviewerId,'approved_at'=>now(),'checksum'=>$checksum,'created_at'=>now(),'updated_at'=>now()]);});}
 public function reject(int $reviewId,int $reviewerId,string $notes=''):void{DB::table('farast_review_cases')->where('id',$reviewId)->update(['reviewer_id'=>$reviewerId,'decision'=>'rejected','status'=>'rejected','notes'=>$notes,'reviewed_at'=>now(),'updated_at'=>now()]);}
 public function createEvaluationCase(string $datasetCode,array $input,array $expected,?int $toolId=null,?int $toolVersionId=null):int{$dataset=DB::table('farast_evaluation_datasets')->where('code',$datasetCode)->orderByDesc('id')->first();if(!$dataset)$datasetId=DB::table('farast_evaluation_datasets')->insertGetId(['code'=>$datasetCode,'version'=>'1.0.0','status'=>'draft','metadata'=>json_encode([]),'created_at'=>now(),'updated_at'=>now()]);else $datasetId=$dataset->id;return (int)DB::table('farast_evaluation_cases')->insertGetId(['dataset_id'=>$datasetId,'tool_id'=>$toolId,'tool_version_id'=>$toolVersionId,'input_payload'=>json_encode($input,JSON_UNESCAPED_UNICODE),'expected_payload'=>json_encode($expected,JSON_UNESCAPED_UNICODE),'status'=>'pending','created_at'=>now(),'updated_at'=>now()]);}
 public function validateToolVersion(int $toolVersionId,float $score):void{DB::table('farast_tool_versions')->where('id',$toolVersionId)->update(['quality_score'=>max(0,min(1,$score)),'evaluation_status'=>$score>=0.8?'approved':'failed','updated_at'=>now()]);}
 public function promoteToolVersion(int $toolVersionId):void{DB::transaction(function()use($toolVersionId){$row=DB::table('farast_tool_versions')->where('id',$toolVersionId)->first();if(!$row||$row->evaluation_status!=='approved'||$row->review_status!=='approved')throw new \RuntimeException('tool_version_not_validated');DB::table('farast_tool_versions')->where('tool_id',$row->tool_id)->where('status','production')->update(['status'=>'retired','updated_at'=>now()]);DB::table('farast_tool_versions')->where('id',$toolVersionId)->update(['status'=>'production','last_verified_at'=>now(),'updated_at'=>now()]);});}
 public function productionKnowledge(string $capability):array{return DB::table('farast_approved_knowledge')->where('capability_code',$capability)->where('status','approved')->orderByDesc('id')->get()->map(fn($x)=>is_string($x->content)?json_decode($x->content,true):$x->content)->all();}
}