@extends('layouts.app')
@section('content')
<style>
.project-create{max-width:1080px;margin:34px auto;padding:0 20px}.project-create__head{text-align:center;margin-bottom:24px}.project-create__head .eyebrow{color:#64748b;font-size:13px}.project-create__head h1{margin:8px 0;font-size:32px}.project-create__head p{margin:0;color:#64748b}.project-step{background:#fff;border:1px solid #e2e8f0;border-radius:24px;padding:28px;box-shadow:0 16px 44px rgba(15,23,42,.07);animation:farast-step .22s ease}.project-question{font-size:21px;font-weight:750;margin:0 0 20px}.project-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.project-card{border:1px solid #e2e8f0;background:#fff;border-radius:18px;padding:18px;min-height:124px;text-align:right;cursor:pointer;transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease}.project-card:hover,.project-card:focus-visible{transform:translateY(-2px);border-color:#94a3b8;box-shadow:0 10px 24px rgba(15,23,42,.08);outline:none}.project-card.is-selected{border-color:#2563eb;box-shadow:0 0 0 3px rgba(37,99,235,.1)}.project-card.is-disabled{opacity:.55;cursor:default}.project-card i{font-size:22px;display:block;margin-bottom:14px}.project-card strong{display:block}.project-card small{display:block;color:#64748b;margin-top:6px;line-height:1.6}.project-back{margin-bottom:16px;border:0;background:none;color:#475569;cursor:pointer;padding:8px}.project-price{margin-top:22px;padding:15px 16px;border-radius:16px;background:#f8fafc;display:flex;justify-content:space-between;align-items:center;gap:12px}.project-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:22px}.project-actions button{min-height:44px;border-radius:12px;padding:0 18px;border:1px solid #cbd5e1;background:#fff;cursor:pointer}.project-actions .primary{background:#0f172a;color:#fff;border-color:#0f172a}.project-note{font-size:13px;color:#64748b;margin:0}.project-progress{display:flex;gap:6px;margin-bottom:18px}.project-progress span{height:4px;flex:1;border-radius:99px;background:#e2e8f0}.project-progress span.active{background:#0f172a}@keyframes farast-step{from{opacity:.6;transform:translateY(4px)}to{opacity:1;transform:none}}@media(max-width:800px){.project-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.project-create{margin:18px auto}.project-step{padding:20px}}@media(max-width:520px){.project-grid{grid-template-columns:1fr}.project-create__head h1{font-size:26px}.project-card{min-height:96px}.project-actions{align-items:stretch;flex-direction:column}.project-actions button{width:100%}}
</style>
<div class="project-create" dir="rtl">
<header class="project-create__head"><span class="eyebrow">FARAST · شروع پروژه</span><h1>پروژه جدید</h1><p>فقط اطلاعاتی را می‌پرسیم که قدم بعدی را تغییر می‌دهد.</p></header>
<section class="project-step">
<div class="project-progress" id="progress" aria-hidden="true"></div>
<button class="project-back" id="back" type="button" hidden>← بازگشت</button>
<h2 class="project-question" id="question">روی چه کاری می‌خواهید کار کنید؟</h2>
<div class="project-grid" id="choices"></div>
<div class="project-price" id="price" hidden><span>برآورد اولیه</span><strong id="priceValue">—</strong></div>
<div class="project-actions"><p class="project-note" id="note">انتخاب شما، مرحله بعد را مشخص می‌کند.</p><button class="primary" id="continue" type="button" disabled>ایجاد پروژه</button></div>
</section>
</div>
<script>
(()=>{const types=@json($types),templates=@json($templates),prices=@json($initialPrices),subscriber=@json($subscriber),choices=document.getElementById('choices'),question=document.getElementById('question'),back=document.getElementById('back'),cont=document.getElementById('continue'),note=document.getElementById('note'),price=document.getElementById('price'),priceValue=document.getElementById('priceValue'),progress=document.getElementById('progress'),answers={};let step='project_type';
const labels={workflow:{manual:'خودم تایپ می‌کنم',voice:'تایپ صوتی',source_file:'تایپ از روی فایل'},source_type:{printed:'متن چاپی',handwritten:'دست‌نویس',mixed:'چاپی + دست‌نویس'},language:{fa:'فارسی',en:'انگلیسی',mixed:'ترکیبی'}};
const icons={manual:'fa-keyboard',voice:'fa-microphone',source_file:'fa-file-arrow-up',printed:'fa-file-lines',handwritten:'fa-pen-nib',mixed:'fa-layer-group',fa:'fa-language',en:'fa-language',mixed:'fa-language'};
const order=['project_type','workflow','source_type','language','template'];
const drawProgress=()=>{const idx=Math.max(0,order.indexOf(step));progress.innerHTML='';for(let i=0;i<5;i++){const x=document.createElement('span');if(i<=idx)x.className='active';progress.appendChild(x)}};
const render=(key)=>{drawProgress();choices.innerHTML='';cont.disabled=true;let items=[];
if(key==='project_type')items=Object.entries(types).map(([id,x])=>({id,title:x.label,sub:x.available?'آماده استفاده':'به‌زودی',icon:x.icon,disabled:!x.available}));
else if(key==='template')items=Object.entries(templates).map(([id,x])=>({id,title:x.name,sub:x.description,icon:'fa-file-lines'}));
else items=Object.entries(labels[key]||{}).map(([id,title])=>({id,title,sub:'',icon:icons[id]||'fa-circle-check'}));
items.forEach(x=>{const b=document.createElement('button');b.type='button';b.className='project-card'+(x.disabled?' is-disabled':'');b.disabled=!!x.disabled;b.innerHTML='<i class="fa-solid '+x.icon+'"></i><strong>'+x.title+'</strong><small>'+x.sub+'</small>';b.onclick=()=>{answers[key]=x.id;next()};choices.appendChild(b)})};
const next=()=>{if(step==='project_type'){if(answers.project_type!=='typing')return;step='workflow'}else if(step==='workflow'){step=answers.workflow==='source_file'?'source_type':answers.workflow==='voice'?'language':'template'}else if(step==='source_type'||step==='language'){step='template'}else if(step==='template'){step='done'};if(step==='done'){question.textContent='پروژه آماده است';choices.innerHTML='<div style="grid-column:1/-1;padding:18px;border:1px solid #e2e8f0;border-radius:16px;background:#f8fafc">سند شما با قالب انتخاب‌شده و تنظیمات لازم ساخته می‌شود.</div>';back.hidden=false;cont.disabled=false;note.textContent='بعد از ایجاد، مستقیماً وارد صفحه سفید سند می‌شوید.';price.hidden=false;renderPrice();drawProgress()}else{question.textContent=step==='workflow'?'چطور می‌خواهید سند را ایجاد کنید؟':step==='source_type'?'منبع شما چه نوعی است؟':step==='language'?'زبان گفتار چیست؟':'قالب سند را انتخاب کنید';back.hidden=false;render(step)}};
const renderPrice=()=>{let base=Number(prices.manual||0);if(answers.workflow==='voice')base=Number(prices.voice||0);if(answers.workflow==='source_file')base=Number(prices[answers.source_type]||0);const multiplier=Number(prices.payg_multiplier_percent||100);const shown=Math.round(base*(subscriber?1:multiplier/100));priceValue.textContent=new Intl.NumberFormat('fa-IR').format(shown)+' ریال / صفحه'+(subscriber?' · سهمیه اشتراک در نظر گرفته می‌شود':' · پرداخت آزاد')};
back.onclick=()=>{if(step==='done')step=answers.workflow==='source_file'?'source_type':answers.workflow==='voice'?'language':'template';else if(step==='template')step=answers.workflow==='source_file'?'source_type':answers.workflow==='voice'?'language':'workflow';else if(step==='source_type'||step==='language')step='workflow';else if(step==='workflow')step='project_type';if(step==='project_type'){back.hidden=true;question.textContent='روی چه کاری می‌خواهید کار کنید؟'}else question.textContent=step==='workflow'?'چطور می‌خواهید سند را ایجاد کنید؟':step==='source_type'?'منبع شما چه نوعی است؟':step==='language'?'زبان گفتار چیست؟':'قالب سند را انتخاب کنید';render(step)};
cont.onclick=async()=>{if(step!=='done')return;cont.disabled=true;note.textContent='در حال ساخت پروژه…';try{const r=await fetch('{{ route('projects.store') }}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({...answers,name:'پروژه تایپ جدید',estimated_pages:1})});const j=await r.json();if(!r.ok)throw new Error(j.message||'ساخت پروژه ناموفق بود');location.href=j.next_url}catch(e){note.textContent=e.message;cont.disabled=false}};
render('project_type');})();
</script>
@endsection
