import http from 'node:http';
import crypto from 'node:crypto';
import { WebSocketServer } from 'ws';
import { SpeechClient } from '@google-cloud/speech';
import sdk from 'microsoft-cognitiveservices-speech-sdk';
const PORT=Number(process.env.PORT||6002), BASE=(process.env.FARAST_BASE_URL||'http://127.0.0.1:8000').replace(/\/$/,''), SECRET=process.env.FARAST_GATEWAY_SECRET||'';
const sessions=new Set();
const sign=v=>crypto.createHmac('sha256',SECRET).update(v).digest('hex');
async function call(path,token,secret=false){const h={'content-type':'application/json','X-Farast-Voice-Gateway':sign(token)};if(secret)h['X-Farast-Voice-Secret']=sign(token);const r=await fetch(BASE+path,{method:'POST',headers:h,body:JSON.stringify({token})});if(!r.ok)throw Error('farast_'+r.status);return r.json()}
const safe=e=>/^[a-z0-9_.:-]{3,120}$/i.test(String(e?.message||''))?String(e.message):'voice_gateway_failure';
class Google{constructor(ws,c){this.ws=ws;this.c=c;this.client=new SpeechClient({credentials:c.credentials});this.s=null}start(){this.s=this.client.streamingRecognize({config:{encoding:'LINEAR16',sampleRateHertz:16000,languageCode:this.c.locale,enableAutomaticPunctuation:true},interimResults:true}).on('data',r=>{const a=r.results?.[0]?.alternatives?.[0];if(!a?.transcript)return;const x=r.results[0];this.ws.send(JSON.stringify({type:x.isFinal?'final':'interim',text:a.transcript,confidence:Number(a.confidence||0)||undefined,stability:Number(x.stability||0)||undefined,sequence:Date.now()}))}).on('error',()=>this.ws.send(JSON.stringify({type:'provider_error',message:'speech_provider_failure'})))}audio(b){this.s?.write(b)}stop(){try{this.s?.end()}catch{}try{this.client.close()}catch{}}}
class Azure{constructor(ws,c){this.ws=ws;this.c=c}start(){const k=this.c.credentials||{};const sc=sdk.SpeechConfig.fromSubscription(String(k.key||k.subscription_key||''),String(k.region||this.c.region||''));sc.speechRecognitionLanguage=this.c.locale;const f=sdk.AudioStreamFormat.getWaveFormatPCM(16000,16,1);this.input=sdk.AudioInputStream.createPushStream(f);this.rec=sdk.SpeechRecognizer(sc,sdk.AudioConfig.fromStreamInput(this.input));this.rec.recognizing=(_,e)=>e.result?.text&&this.ws.send(JSON.stringify({type:'interim',text:e.result.text,stability:.5}));this.rec.recognized=(_,e)=>e.result?.text&&this.ws.send(JSON.stringify({type:'final',text:e.result.text,sequence:Date.now()}));this.rec.startContinuousRecognitionAsync()}audio(b){this.input?.write(b)}stop(){try{this.input?.close()}catch{}try{this.rec?.stopContinuousRecognitionAsync(()=>this.rec?.close())}catch{}}}
async function startSession(ws,m){if(sessions.size>=Number(process.env.MAX_VOICE_SESSIONS||32))throw Error('voice_gateway_capacity');const auth=await call('/editor/voice/stream-config',m.token);if(auth.locale!==m.locale)throw Error('voice_locale_mismatch');const c=await call('/editor/voice/provider-config',m.token,true);c.locale=m.locale;let s;switch(String(c.provider).toLowerCase()){case'google':case'google-cloud-speech':case'google-cloud-speech-v1':s=new Google(ws,c);break;case'azure':case'azure-speech':case'microsoft-azure-speech':s=new Azure(ws,c);break;default:throw Error('voice_provider_adapter_unavailable')}s.start();sessions.add(s);return s}
const server=http.createServer((_,r)=>{r.writeHead(200,{'content-type':'application/json'});r.end(JSON.stringify({ok:true,service:'farast-voice-gateway',active_sessions:sessions.size}))});
const wss=new WebSocketServer({server,maxPayload:65536});wss.on('connection',ws=>{let s=null;ws.on('message',async(d,b)=>{try{if(!s){if(b)throw Error('voice_session_not_started');const m=JSON.parse(d.toString());if(m.type!=='start'||!m.token)throw Error('voice_session_invalid');s=await startSession(ws,m);ws.send(JSON.stringify({type:'ready',provider:'server-side'}));return}if(b){s.audio(Buffer.from(d));return}const m=JSON.parse(d.toString());if(m.type==='stop'){s.stop();s=null;ws.close(1000,'normal')}}catch(e){ws.send(JSON.stringify({type:'error',message:safe(e)}));if(!s)ws.close(1011,'gateway_error')}});ws.on('close',()=>{try{s?.stop()}catch{}if(s)sessions.delete(s)})});
server.listen(PORT,()=>console.log('FARAST voice gateway listening on '+PORT));