<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  if (!Schema::hasTable('document_folders')) Schema::create('document_folders',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('name',120);$t->foreignId('parent_id')->nullable()->constrained('document_folders')->nullOnDelete();$t->boolean('is_favorite')->default(false);$t->timestamps();$t->index(['user_id','parent_id']);});
  if (!Schema::hasTable('farast_documents')) Schema::create('farast_documents',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('folder_id')->nullable()->constrained('document_folders')->nullOnDelete();$t->string('title',255);$t->longText('content')->nullable();$t->string('status',30)->default('active');$t->boolean('is_favorite')->default(false);$t->timestamp('trashed_at')->nullable();$t->timestamps();$t->index(['user_id','status','updated_at']);});
  if (!Schema::hasTable('farast_document_versions')) Schema::create('farast_document_versions',function(Blueprint $t){$t->id();$t->foreignId('document_id')->constrained('farast_documents')->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->longText('content')->nullable();$t->string('label',160)->nullable();$t->timestamps();$t->index(['document_id','created_at']);});
  if (!Schema::hasTable('farast_document_shares')) Schema::create('farast_document_shares',function(Blueprint $t){$t->id();$t->foreignId('document_id')->constrained('farast_documents')->cascadeOnDelete();$t->foreignId('owner_id')->constrained('users')->cascadeOnDelete();$t->foreignId('shared_with_user_id')->nullable()->constrained('users')->cascadeOnDelete();$t->string('token',80)->unique();$t->string('permission',20)->default('view');$t->timestamp('expires_at')->nullable();$t->timestamps();});
  if (!Schema::hasTable('farast_notifications')) Schema::create('farast_notifications',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('type',60);$t->string('title',255);$t->text('body')->nullable();$t->json('data')->nullable();$t->timestamp('read_at')->nullable();$t->timestamps();$t->index(['user_id','read_at','created_at']);});
  if (!Schema::hasTable('farast_workflows')) Schema::create('farast_workflows',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->boolean('enabled')->default(true);$t->string('trigger_type',40);$t->json('steps');$t->timestamps();});
  if (!Schema::hasTable('farast_workflow_runs')) Schema::create('farast_workflow_runs',function(Blueprint $t){$t->id();$t->foreignId('workflow_id')->constrained('farast_workflows')->cascadeOnDelete();$t->string('status',30)->default('queued');$t->json('context')->nullable();$t->text('error')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->timestamps();$t->index(['workflow_id','created_at']);});
  if (!Schema::hasTable('farast_plans')) Schema::create('farast_plans',function(Blueprint $t){$t->id();$t->string('code',80)->unique();$t->string('name',120);$t->unsignedBigInteger('price')->default(0);$t->string('currency',8)->default('IRR');$t->json('quotas')->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  if (!Schema::hasTable('farast_subscriptions')) Schema::create('farast_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('plan_id')->constrained('farast_plans')->restrictOnDelete();$t->string('status',30)->default('active');$t->timestamp('starts_at');$t->timestamp('ends_at')->nullable();$t->timestamps();$t->index(['user_id','status']);});
  if (!Schema::hasTable('farast_usage_counters')) Schema::create('farast_usage_counters',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('metric',80);$t->unsignedBigInteger('used')->default(0);$t->unsignedBigInteger('period_limit')->nullable();$t->date('period_start');$t->date('period_end');$t->timestamps();$t->unique(['user_id','metric','period_start']);});
  if (!Schema::hasTable('farast_cms_pages')) Schema::create('farast_cms_pages',function(Blueprint $t){$t->id();$t->string('slug',160)->unique();$t->string('title',255);$t->longText('body')->nullable();$t->string('status',20)->default('draft');$t->timestamp('published_at')->nullable();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
  if (!Schema::hasTable('farast_security_events')) Schema::create('farast_security_events',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('event',80);$t->ipAddress('ip')->nullable();$t->text('user_agent')->nullable();$t->json('meta')->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['user_id','created_at']);});
  if (!Schema::hasTable('farast_ocr_jobs')) Schema::create('farast_ocr_jobs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('provider',50)->default('auto');$t->string('status',30)->default('queued');$t->string('source_path')->nullable();$t->longText('result_text')->nullable();$t->text('error')->nullable();$t->timestamps();});
  if (!Schema::hasTable('farast_canva_assets')) Schema::create('farast_canva_assets',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('canva_connection_id')->nullable()->constrained()->nullOnDelete();$t->string('design_id',180);$t->string('name',255)->nullable();$t->string('thumbnail_url',1000)->nullable();$t->string('edit_url',1000)->nullable();$t->string('status',40)->nullable();$t->json('metadata')->nullable();$t->timestamp('synced_at')->nullable();$t->timestamps();$t->unique(['user_id','design_id']);});
 }
 public function down(): void { foreach(['farast_canva_assets','farast_ocr_jobs','farast_security_events','farast_cms_pages','farast_usage_counters','farast_subscriptions','farast_plans','farast_workflow_runs','farast_workflows','farast_notifications','farast_document_shares','farast_document_versions','farast_documents','document_folders'] as $t) if(Schema::hasTable($t)) Schema::drop($t); }
};