<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PlatformCompletionController extends Controller {
 private function doc(Request $r,$id){$d=DB::table('farast_documents')->where('id',$id)->where('user_id',auth()->id())->first();abort_unless($d,404);return $d;}
 public function documents(Request $r){$q=DB::table('farast_documents')->where('user_id',auth()->id())->where('status','active');if($r->filled('favorite'))$q->where('is_favorite',1);if($r->filled('folder'))$q->where('folder_id',$r->integer('folder'));return view('platform.documents',['documents'=>$q->orderByDesc('updated_at')->paginate(24),'folders'=>DB::table('document_folders')->where('user_id',auth()->id())->orderBy('name')->get()]);}
 public function createDocument(Request $r){$d=$r->validate(['title'=>'required|string|max:255','content'=>'nullable|string','folder_id'=>'nullable|integer']);$id=DB::table('farast_documents')->insertGetId(['user_id'=>auth()->id(),'title'=>$d['title'],'content'=>$d['content']??'','folder_id'=>$d['folder_id']??null,'created_at'=>now(),'updated_at'=>now()]);DB::table('farast_document_versions')->insert(['document_id'=>$id,'user_id'=>auth()->id(),'content'=>$d['content']??'','label'=>'نسخه اولیه','created_at'=>now(),'updated_at'=>now()]);return redirect()->route('platform.documents')->with('status','سند ایجاد شد.');}
 public function updateDocument(Request $r,$id){$d=$this->doc($r,$id);$x=$r->validate(['title'=>'required|string|max:255','content'=>'nullable|string','folder_id'=>'nullable|integer']);DB::table('farast_documents')->where('id',$id)->update(['title'=>$x['title'],'content'=>$x['content']??'','folder_id'=>$x['folder_id']??null,'updated_at'=>now()]);DB::table('farast_document_versions')->insert(['document_id'=>$id,'user_id'=>auth()->id(),'content'=>$x['content']??'','label'=>$r->input('version_label'),'created_at'=>now(),'updated_at'=>now()]);return back()->with('status','سند ذخیره شد.');}
 public function favorite(Request $r,$id){$d=$this->doc($r,$id);DB::table('farast_documents')->where('id',$id)->update(['is_favorite'=>!$d->is_favorite,'updated_at'=>now()]);return back();}
 public function trash(Request $r,$id){$this->doc($r,$id);DB::table('farast_documents')->where('id',$id)->update(['status'=>'trashed','trashed_at'=>now()]);return back();}
 public function restore(Request $r,$id){DB::table('farast_documents')->where('id',$id)->where('user_id',auth()->id())->update(['status'=>'active','trashed_at'=>null,'updated_at'=>now()]);return back();}
 public function destroy(Request $r,$id){DB::table('farast_documents')->where('id',$id)->where('user_id',auth()->id())->delete();return back();}
 public function versions(Request $r,$id){$this->doc($r,$id);return response()->json(DB::table('farast_document_versions')->where('document_id',$id)->orderByDesc('created_at')->get());}
 public function share(Request $r,$id){$this->doc($r,$id);$x=$r->validate(['permission'=>'nullable|in:view,edit','expires_at'=>'nullable|date']);$token=Str::random(48);DB::table('farast_document_shares')->insert(['document_id'=>$id,'owner_id'=>auth()->id(),'token'=>$token,'permission'=>$x['permission']??'view','expires_at'=>$x['expires_at']??null,'created_at'=>now(),'updated_at'=>now()]);return response()->json(['url'=>url('/shared/documents/'.$token),'permission'=>$x['permission']??'view']);}
 public function shared($token){$s=DB::table('farast_document_shares')->where('token',$token)->first();abort_unless($s && (!$s->expires_at || now()->lt($s->expires_at)),404);$d=DB::table('farast_documents')->find($s->document_id);abort_unless($d,404);return view('platform.shared-document',compact('d','s'));}
 public function notifications(){return view('platform.notifications',['items'=>DB::table('farast_notifications')->where('user_id',auth()->id())->orderByDesc('created_at')->paginate(30)]);}
 public function readNotification(Request $r,$id){DB::table('farast_notifications')->where('id',$id)->where('user_id',auth()->id())->update(['read_at'=>now()]);return back();}
 public function workflow(Request $r){$items=DB::table('farast_workflows')->where('user_id',auth()->id())->get();return view('platform.workflows',compact('items'));}
 public function saveWorkflow(Request $r){$x=$r->validate(['name'=>'required|string|max:160','trigger_type'=>'required|string|max:40','steps'=>'required|array']);DB::table('farast_workflows')->updateOrInsert(['id'=>$r->integer('id'),'user_id'=>auth()->id()],['name'=>$x['name'],'trigger_type'=>$x['trigger_type'],'steps'=>json_encode($x['steps'],JSON_UNESCAPED_UNICODE),'enabled'=>$r->boolean('enabled',true),'updated_at'=>now(),'created_at'=>now()]);return back()->with('status','گردش‌کار ذخیره شد.');}
 public function runWorkflow(Request $r,$id){$w=DB::table('farast_workflows')->where('id',$id)->where('user_id',auth()->id())->first();abort_unless($w,404);$run=DB::table('farast_workflow_runs')->insertGetId(['workflow_id'=>$id,'status'=>'queued','context'=>json_encode($r->input('context',[])),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['run_id'=>$run,'status'=>'queued']);}
 public function security(){return view('platform.security',['events'=>DB::table('farast_security_events')->where('user_id',auth()->id())->latest()->limit(50)->get()]);}
 public function ocr(Request $r){$x=$r->validate(['source_path'=>'required|string|max:1000','provider'=>'nullable|string|max:50']);$id=DB::table('farast_ocr_jobs')->insertGetId(['user_id'=>auth()->id(),'source_path'=>$x['source_path'],'provider'=>$x['provider']??'auto','status'=>'queued','created_at'=>now(),'updated_at'=>now()]);return response()->json(['job_id'=>$id,'status'=>'queued']);}
 public function ocrStatus(Request $r,$id){$j=DB::table('farast_ocr_jobs')->where('id',$id)->where('user_id',auth()->id())->first();abort_unless($j,404);return response()->json($j);}
 public function cms(Request $r){abort_unless(auth()->user()->isAdmin(),403);return view('admin.cms',['pages'=>DB::table('farast_cms_pages')->orderByDesc('updated_at')->get()]);}
 public function saveCms(Request $r){abort_unless(auth()->user()->isAdmin(),403);$x=$r->validate(['slug'=>'required|string|max:160','title'=>'required|string|max:255','body'=>'nullable|string','status'=>'required|in:draft,published']);DB::table('farast_cms_pages')->updateOrInsert(['slug'=>$x['slug']],['title'=>$x['title'],'body'=>$x['body']??'','status'=>$x['status'],'published_at'=>$x['status']==='published'?now():null,'updated_by'=>auth()->id(),'updated_at'=>now(),'created_at'=>now()]);return back()->with('status','صفحه CMS ذخیره شد.');}
}